name: 'Quality Checks'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['type-check', 'test:unit']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Install packages'
        run: npm i
      - name: 'Run ${{ matrix.command }}'
        run: npm run ${{ matrix.command }}
